### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by mimranmani** [WGLab/InterVar#18]
Hi
I am getting this error when I am running the program with and without the annovar
  
Traceback (most recent call last):
  File "Intervar.py", line 2051, in <module>
    main()
  File "Intervar.py", line 2013, in main
    read_datasets()
  File "Intervar.py", line 364, in read_datasets
    BS2_snps_recess_dict[ keys ]=cls2[4]  # key as snp info
MemoryError

**Comment by quanliustc** [comment]
This dataset has about 5,671,385 records, not very big,
What's your version of python? Are you using InterVar  in Windows or Linux? 32 or 64 bit?
