### ISSUE TITLE
Error reading bs2_snps with python version 2.17.3 or higher

### ISSUE THREAD

**Issue by timjeske** [WGLab/InterVar#22]
Here is the error message that occurs:

Traceback (most recent call last):
  File "/home/jeske/tools/InterVar/Intervar.py", line 2066, in <module>
    main()
  File "/home/jeske/tools/InterVar/Intervar.py", line 2028, in main
    read_datasets()
  File "/home/jeske/tools/InterVar/Intervar.py", line 358, in read_datasets
    for line2 in strs.split('\n'):
TypeError: a bytes-like object is required, not 'str'

**Comment by quanliustc** [comment]
fix for python3.5
